[project]
name = "mir-semantics"
version = "0.1.0"
source = "k-src"

[targets.llvm]
backend = "llvm"
main-file = "mir.md"
syntax-module = "MIR-PARSER-SYNTAX"

[targets.haskell]
backend = "haskell"
main-file = "mir.md"
syntax-module = "MIR-PARSER-SYNTAX"