load("//:k.bzl", "kast_test")

kast_test(
  name = 'const-struct-kast',
  src = 'const-struct.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'rvalue-variable-kast',
  src = 'rvalue-variable.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'lvalue-variable-kast',
  src = 'lvalue-variable.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'const-int-kast',
  src = 'const-int.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'rvalue-move-kast',
  src = 'rvalue-move.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'rvalue-const-kast',
  src = 'rvalue-const.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'basic-blocks-kast',
  src = 'basic-blocks.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'function-empty-kast',
  src = 'function-empty.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'terminator-call-assignment-kast',
  src = 'terminator-call-assignment.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'const-strings-kast',
  src = 'const-strings.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'lvalue-as-kast',
  src = 'lvalue-as.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'terminator-goto-kast',
  src = 'terminator-goto.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'scope-kast',
  src = 'scope.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'const-empty-tuple-kast',
  src = 'const-empty-tuple.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'const-float-kast',
  src = 'const-float.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'lvalue-dereference-kast',
  src = 'lvalue-dereference.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'terminator-return-kast',
  src = 'terminator-return.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'rvalue-move-list-kast',
  src = 'rvalue-move-list.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'scope-debug-kast',
  src = 'scope-debug.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'function-for-constant-named-kast',
  src = 'function-for-constant-named.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'const-enum-kast',
  src = 'const-enum.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'rvalue-discriminant-kast',
  src = 'rvalue-discriminant.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'lvalue-typed-field-kast',
  src = 'lvalue-typed-field.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'const-enum-cast-kast',
  src = 'const-enum-cast.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'scope-scope-kast',
  src = 'scope-scope.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'statement-list-kast',
  src = 'statement-list.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'const-alloc-kast',
  src = 'const-alloc.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'terminator-call-destination-kast',
  src = 'terminator-call-destination.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'function-path-location-kast',
  src = 'function-path-location.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'rvalue-ampersand-kast',
  src = 'rvalue-ampersand.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'function-parameters-kast',
  src = 'function-parameters.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'terminator-call-assignment-destination-kast',
  src = 'terminator-call-assignment-destination.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'rvalue-as-kast',
  src = 'rvalue-as.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'rvalue-const-list-kast',
  src = 'rvalue-const-list.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'statement-assignment-to-discriminant-kast',
  src = 'statement-assignment-to-discriminant.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'const-bool-kast',
  src = 'const-bool.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'lvalue-typed-field-complex-kast',
  src = 'lvalue-typed-field-complex.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'terminator-call-kast',
  src = 'terminator-call.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'rvalue-len-kast',
  src = 'rvalue-len.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'scope-binding-kast',
  src = 'scope-binding.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'function-path-simple-kast',
  src = 'function-path-simple.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'bindings-kast',
  src = 'bindings.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'rvalue-empty-list-kast',
  src = 'rvalue-empty-list.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'scope-complex-kast',
  src = 'scope-complex.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'lvalue-indexing-kast',
  src = 'lvalue-indexing.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'statement-assignment-kast',
  src = 'statement-assignment.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'function-for-constant-anonymous-kast',
  src = 'function-for-constant-anonymous.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'mir-multiple-functions-kast',
  src = 'mir-multiple-functions.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'rvalue-operators-kast',
  src = 'rvalue-operators.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)

kast_test(
  name = 'lvalue-dereference-complex-kast',
  src = 'lvalue-dereference-complex.mir',
  semantics = '//semantics:mir',
  sort = 'Mir',
  size = 'small',
)
