name: Proofs

on:
  push:
    branches: [proofs]
  pull_request:
    branches: [proofs]

jobs:
  format_and_lint_ptoken:
    name: Format & Lint p-token
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          clippy: true
          rustfmt: true

      - name: Format
        run: pnpm p-token:format

      - name: Lint
        run: pnpm p-token:lint