name: "Release KMIR"

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: [self-hosted, linux, normal]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: 'Setup Docker Buildx'
        uses: docker/setup-buildx-action@v3.10.0
          
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set K_VERSION
        id: k_version
        run: |
          echo "K_VERSION=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ghcr.io/runtimeverification/mir-semantics/kmir:ubuntu-jammy-${{ steps.k_version.outputs.K_VERSION }}
          